const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM_FROM_CARD: 'CLEAR_ITEM_FROM_CARD',
  REMOVE_ITEM: 'REMOVE_ITEM'
};

export default CartActionTypes;
